### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by ZigzagAwaka** [xntkrnl/WiderShipMod#1]
Hello
Can you add compatibility for the Windows mod https://thunderstore.io/c/lethal-company/p/TestAccount666/ShipWindows/ ?
With that, it should be compatible with mods that allows players to go out in space (CelestialTint for example)

**Comment by ZigzagAwaka** [comment]
Or maybe you are already planing to add new stuff for this mod ? The goal is to simply make the ship bigger or making something new entirely ?

**Comment by xntkrnl** [comment]
Hello, I plan to make this mod compatible in the future. Initially this mod was supposed to be a simple test of replacing assets in the game on the ship/the ship itself, but I decided to post it because I'm pretty happy with the result (despite the code). There are a couple of things I'd like to add in the future like buying an upgrade that expands the ship. Thank you for your interest.

**Comment by ZigzagAwaka** [comment]
Oh boy that's better than i thought then, keep up the great work !
Also, having it as a ship upgrade (or at least, a possible config option for those who want to) is perfect, really

**Comment by ilkankuss** [comment]
I made an account just to ask for this. I look forward to it. Playing with 20 people makes you want a bigger ship LOL.

**Comment by meBVH** [comment]
Hi! Has there been any progress on this project? Mod hasn't been updated on Thunderstore for two months now.

**Comment by ZigzagAwaka** [comment]
Windows compatibility is still not a thing, but you can check the 2 story ship mod if you want that is compatible with Wider ship and Ship windows

**Comment by xntkrnl** [comment]
1.3.0 is out, compatibility has been added
